################################################################################################ Lobby

lobby-hotbar:
  icons:
  - slot: 8
    item:
      type: bed
      name: '&c&lReturn to Lobby'
      lore:
      - '&7Right-click to leave to the lobby!'
    click:
      actions:
      - command:
          command: quake quit
          executor: player

waiting-board:
  title: '&e&lQUAKECRAFT'
  lines:
  - ''
  - '&fMap: &a%arena_name%'
  - '&fPlayers: &a%players%/%max_players%'
  - ''
  - '&fWaiting...'
  - ''
  - '&ewww.upperlevel.xyz'

countdown-timer: 10
countdown-messages:
  40: '&eThe game is starting within &b40&e seconds!'
  20: '&eThe game is starting within 20 seconds!'
  # 30: 'At 30 seconds it would write this message! But it does not because it is commented out'
  10: '&eThe game starts in &610&e seconds!'
  5:  '&eThe game starts in &c5&e seconds!'
  4:  '&eThe game starts in &c4&e seconds!'
  3:  '&eThe game starts in &c3&e seconds!'
  2:  '&eThe game starts in &c2&e seconds!'
  1:  '&eThe game starts in &c1&e second!'
  0: # The 0th second is when the game starts

countdown-sounds:
  5: 'BLOCK_DISPENSER_FAIL'
  4: 'BLOCK_DISPENSER_FAIL'
  3: 'BLOCK_DISPENSER_FAIL'
  2: 'BLOCK_DISPENSER_FAIL'
  1: 'BLOCK_DISPENSER_FAIL'

countdown-board:
  title: '&e&lQUAKECRAFT'
  lines:
  - ''
  - '&fMap: &a%arena_name%'
  - '&fPlayers: &a%players%/%max_players%'
  - ''
  - '&fStarting in &a%countdown%s'
  - ''
  - '&eupperlevel.github.io'

################################################################################################ Game

start-message:
- '^a'
- '^|&fQuakecraft'
- ''
- '^|Right-click with your Railgun to shoot'
- '^|the enemy before they shoot you!'
- '^|Left-click with it to Dash and dodge!'
- ''
- '^a'

start-sound: 'ENTITY_PLAYER_LEVELUP'

dash-power: 1.5 # basic dash power that'll be multiplied with the upgrades
dash-cooldown-message: '&cDash cooling down! %remaining_secs%s remaining!'

gain-message: '&6+%gain_amount%! (%gain_name% Bonus)'
on-gain: '&6+%raw_gain%'

kill-gain:
  name: 'Kill'
  amount: 1

headshot-gain:
  name: 'Headshot'
  amount: 2

base-gain: # Given every time you finish a game
  amount: 2

1-place-gain:
  amount: 10

2-place-gain:
  amount: 5

3-place-gain:
  amount: 3

game-countdown: 600  # in seconds (600 = 10 minutes)
game-board:
  title: '&e&lQUAKECRAFT'
  update-interval: 10
  header:
  - ''
  - '&fTime left: &a%game_countdown%'
  - ''
  ranking:
    text: '&7%player_name%: &a%kills%'
    size: 12
  footer:
  - ''
  - '&ewww.upperlevel.xyz'

default-kill-message: '&7shot'
shot-message: '&7%killer% %kill_message% &7%killed%'
headshot-message: '&7%killer% %kill_message% &7%killed% &e&lHEADSHOT'

sneak-disabled: true
sneak-disabled-message: '&cSneaking is disabled! Your name is still visible'

kills-to-win: 20

playing-hotbar:
  gun:
    slot: 0
  item:
    name: '&7Railgun'
    lore:
    - '&7Case: &a%case%'
    - '&7Laser: &a%laser%'
    - '&7Barrel: &a%barrel%'
    - '&7Muzzle: &a%muzzle%'
    - '&7Trigger: &a%trigger%'
    - ''
    - '&eRight-click to shoot!'
    - '&eLeft-click to dash forward!'
  tracker:
    slot: 1
    item:
      name: '&aTracking Device'
      lore:
      - '&7Points the closest enemy!'

ending-hotbar:
  icons:
  - slot: 8
    item:
      type: bed
      name: '&c&lReturn to Lobby'
      lore:
      - '&7Right-click to leave to the lobby!'
