name: QuakeCraftReloaded
version: ${project.version}
main: xyz.upperlevel.spigot.quakecraft.QuakeCraftReloaded
author: [upperlevel]

depend: [UpperCore]
softdepend: [PlaceholderAPI]

commands:
  quake:
    description: 'Main commands of QuakeCraftReloaded.'