name: Quakecraft
version: ${project.version}
main: xyz.upperlevel.quakecraft.Quakecraft

depend: [UpperCore]
softdepend: [PlaceholderAPI]

commands:
  quake:
    description: 'Main commands of Quakecraft.'