# For every muzzle you can write one or more particles of various types,
# Every particle by default has some config values, but others are only available with certain particle types,
# The default values are
# particle:
#   speed: 0.05 # The speed of the particle
#   amount: 10 # Particle amount
#   offset:
#     x: 0
#     y: 0
#     z: 0
# Then you can specify the particle type with the "type" value, the SIMPLE particle is a simple coloured particle,
# a BLOCK_DUST particle is a particle that has as texture the specified block's texture
# a SIMPLE particle has the custom value "color" thar represents the color of the particle,
# particle:
#   type: 'SIMPLE'
#   color: 'BLUE' #Or R;G;B or even #hex
#
# A  BLOCK_DUST particle has the custom value "block" that represents the displayed block type
# particle:
#   type: 'BLOCK_DUST'
#   block:
#     type: 'LAPIS_BLOCK'
#     data: 0 # Optional
none:
  name: 'No Muzzle'
  cost: 0
  default: true
  icon:
    type: 'GLASS'
    lore:
    - '&7Choose a particle effect!'
  particles:
    - type: 'SIMPLE'
      color: 'RED'

clay:
  name: 'Clay Muzzle'
  cost: 5000
  icon:
    type: 'CLAY'
    lore:
    - '&7Choose a particle effect!'
  particles:
  - type: 'BLOCK_DUST'
    block:
      type: 'CLAY'

wood:
  name: 'Wooden Muzzle'
  cost: 5000
  icon:
    type: 'WOOD'
    lore:
    - '&7Choose a particle effect!'
  particles:
  - type: 'BLOCK_DUST'
    block:
      type: 'WOOD'

gold:
  name: 'Golden Muzzle'
  cost: 7500
  icon:
    type: 'GOLD_BLOCK'
    lore:
    - '&7Choose a particle effect!'
  particles:
  - type: 'BLOCK_DUST'
    block:
      type: 'GOLD_BLOCK'

redstone:
  name: 'Redstone Muzzle'
  cost: 7500
  icon:
    type: 'REDSTONE_BLOCK'
    lore:
    - '&7Choose a particle effect!'
  particles:
  - type: 'BLOCK_DUST'
    block:
      type: 'REDSTONE_BLOCK'

iron:
  name: 'Iron Muzzle'
  cost: 8200
  icon:
    type: 'IRON_BLOCK'
    lore:
    - '&7Choose a particle effect!'
  particles:
  - type: 'BLOCK_DUST'
    block:
      type: 'IRON_BLOCK'

ender_stone:
  name: 'Ender Stone Muzzle'
  cost: 8500
  icon:
    type: 'ENDER_STONE'
    lore:
    - '&7Choose a particle effect!'
  particles:
  - type: 'BLOCK_DUST'
    block:
      type: 'ENDER_STONE'

diamond:
  name: 'Diamond Muzzle'
  cost: 9000
  icon:
    type: 'DIAMOND_BLOCK'
    lore:
    - '&7Choose a particle effect!'
  particles:
  - type: 'BLOCK_DUST'
    block:
      type: 'DIAMOND_BLOCK'

quartz:
  name: 'Quartz Muzzle'
  cost: 15000
  icon:
    type: 'QUARTZ_ORE'
    lore:
    - '&7Choose a particle effect!'
  particles:
  - type: 'BLOCK_DUST'
    block:
      type: 'QUARTZ_ORE'

emerald:
  name: 'Emerald Muzzle'
  cost: 25000
  icon:
    type: 'EMERALD_BLOCK'
    lore:
    - '&7Choose a particle effect!'
  particles:
  - type: 'BLOCK_DUST'
    block:
      type: 'EMERALD_BLOCK'

lapis:
  name: 'Lapis Muzzle'
  cost: 25000
  icon:
    type: 'LAPIS_BLOCK'
    lore:
    - '&7Choose a particle effect!'
  particles:
  - type: 'BLOCK_DUST'
    block:
      type: 'LAPIS_BLOCK'

obsidian:
  name: 'Obsidian Muzzle'
  cost: 50000
  icon:
    type: 'OBSIDIAN'
    lore:
    - '&7Choose a particle effect!'
  particles:
  - type: 'BLOCK_DUST'
    block:
      type: 'OBSIDIAN'

sponge:
  name: 'Sponge Muzzle'
  cost: 50000
  icon:
    type: 'SPONGE'
    lore:
    - '&7Choose a particle effect!'
  particles:
  - type: 'BLOCK_DUST'
    block:
      type: 'SPONGE'

sea_lantern:
  name: 'Sea Lantern Muzzle'
  cost: 75000
  icon:
    type: 'SEA_LANTERN'
    lore:
    - '&7Choose a particle effect!'
  particles:
  - type: 'BLOCK_DUST'
    block:
      type: 'SEA_LANTERN'

command_block:
  name: 'Command Block Muzzle'
  cost: 100000
  icon:
    type: 'COMMAND'
    lore:
    - '&7Choose a particle effect!'
  particles:
  - type: 'BLOCK_DUST'
    block:
      type: 'COMMAND'

prismarine:
  name: 'Prismarine Muzzle'
  cost: 100000
  icon:
    type: 'PRISMARINE'
    lore:
    - '&7Choose a particle effect!'
  particles:
  - type: 'BLOCK_DUST'
    block:
      type: 'PRISMARINE'

melon:
  name: 'Melon Muzzle'
  cost: 125000
  icon:
    type: 'MELON_BLOCK'
    lore:
    - '&7Choose a particle effect!'
  particles:
  - type: 'BLOCK_DUST'
    block:
      type: 'MELON_BLOCK'

pumpkin:
  name: 'Pumpkin Muzzle'
  cost: 100000
  icon:
    type: 'PUMPKIN'
    lore:
    - '&7Choose a particle effect!'
  particles:
  - type: 'BLOCK_DUST'
    block:
      type: 'PUMPKIN'

soul_sand:
  name: 'Soul Sand Muzzle'
  cost: 500000
  icon:
    type: 'SOUL_SAND'
    lore:
    - '&7Choose a particle effect!'
  particles:
  - type: 'BLOCK_DUST'
    block:
      type: 'SOUL_SAND'
