title: 'Case'
size: 54
icons:
- slot: 48
  item:
    type: 'arrow'
    name: '&aGo Back'
  click:
    actions:
    - 'gui-back'
slots: [
  11, 12, 13, 14, 15,
  20, 21, 22, 23, 24,
  29, 30, 31, 32, 33
]
