icons:
- slot: 8
  item:
    type: bed
    name: '&c&lReturn to Lobby'
    lore:
    - '&7Right-click to leave to the lobby!'
  click:
    actions:
    - command:
        command: quake quit
        executor: player